# Generated by Django 2.2.5 on 2020-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberstories',
            name='Description',
            field=models.TextField(max_length=264),
        ),
    ]
