# Generated by Django 2.2.5 on 2020-03-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0005_cyberstories_storyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRPComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NCRPNumber', models.CharField(max_length=15)),
                ('ComplaintDistrict', models.CharField(max_length=30)),
                ('ComplaintAction', models.CharField(max_length=264)),
            ],
        ),
    ]
