# Generated by Django 2.2.5 on 2020-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0006_ncrpcomplaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrpcomplaints',
            name='AccusedEmailID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ncrpcomplaints',
            name='AccusedPhoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrpcomplaints',
            name='ActionTaken',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='ncrpcomplaints',
            name='ComplaintCategory',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='ncrpcomplaints',
            name='ComplaintPoliceStation',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='ncrpcomplaints',
            name='ComplaintSubCategory',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='ncrpcomplaints',
            name='FIRorCSRNumber',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='ncrpcomplaints',
            name='ComplaintAction',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
