# Generated by Django 2.2.5 on 2020-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=264)),
                ('Link', models.CharField(max_length=264)),
                ('Published', models.CharField(max_length=264)),
                ('Description', models.CharField(max_length=264)),
            ],
        ),
    ]
